apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: mlserver
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  serverConfig: mlserver
---
apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: triton
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  serverConfig: triton
